name: CI/CD Pipeline for Green Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        cd ~/zero-downtime-app
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Flask application
      run: |
        cd ~/zero-downtime-app
        source venv/bin/activate
        python app.py
